# This config defines the custom neuralbody + background of lightstage
parents:
  - config/neuralbody/dataset/neuralbody_custom.yml

data_share_args:
  ranges: [0, 300, 1]
  subs: ['1','2','3','4','5','6','7']
  image_args:
    mask_bkgd: False
    unsync: output-smpl-3d/time_offset.json
  sample_args:
    nrays: 8192
  object_args:
    allhuman:
      pids: [0]
      model: neuralbody-smplmask
      rate: 1
      args:
        pid: -1
        use_param_foreachview: True
        rate_body: 0.95
        reader:
          _no_merge_: True
          smpl:
            root: output-smpl-3d/smpl
          vertices:
            root: output-smpl-3d/vertices
            padding: 0.05
          mask:
            root: output-smpl-3d/instance
            undis: False # don't undis as it is rendered by KRT
          label:
            root: output-keypoints3d/label
            undis: False # don't undis as it is rendered by undistorted
    background:
      model: cylinder
      rate: 0.05
      args:
        center: [0., 0., 0.]
        radius: [12., 15.]
        zranges: [0.01, 5.]
    ground:
      model: plane
      rate: 0.05
      args:
        center: [0., 0., 0.]
        radius: 12.
        zranges: [-0.01, 0.01]

data_demo_args:
  object_keys: []
  ignore_keys: [background]
  object_args:
    ground:
      args:
        xybounds: [-12, 12]
  camera_args:
    method: mean
    center: [0., 0.]
    H: 1080
    W: 1920
    allstep: 300