data: config/datasets/mvimage.yml
exp: config/mvmp/detect_match_triangulate_fitSMPL.yml
data_opts:
  root: TO_BE_FILLED
  subs: []
  subs_vis: ['cam1', 'cam2', 'cam3', 'cam4', 'cam5', 'cam6', 'cam7']
  ranges: [0, 300, 1]
exp_opts:
  output: output/wildtrack
  at_step:
    detect:
      args:
        min_length: 0
        max_length: 2000
    match:
      args:
        cfg_match:
          distance:
            threshold_track: 0.05
          triangulate:
            min_view: 3 # at least 3 views to triangulate
            min_view_body: 3 # at least 5 views to triangulate
            dist_max: 25 # pixel
            dist_track: 100 # 100mm；
        cfg_track:
          max_person: 100
          final_ranges: [[0, 0, 0.], [2000, 800, 100]] # 最终的输出的range，仅用于输出的时候的筛选
          final_max_person: 100
  at_final:
    collect:
      args:
        min_frame: 100
    fitting_each_person:
      args:
        stages:
          refine_poses:
            args:
              loss:
                smooth:
                  weight: 5.
    vis_render:
      args:
        view_list: [2]
        scale: 1.