data: config/datasets/mvimage.yml
exp: config/mvmp/gt_bbox_triangulate_fitSMPL.yml
data_opts:
  root: TO_BE_FILLED
  subs: ['1','2','3','4','5','6','7']
  subs_vis: ['1','2','3','4','5','6','7']
  ranges: [0, 300, 1]
exp_opts:
  output: output/wildtrack
  at_step:
    detect:
      args:
        folder: data/wildtrack/annotations_positions
    match:
      args:
        cfg_match:
          distance:
            threshold_track: 0.05
          triangulate:
            min_view: 2 # at least 3 views to triangulate
            min_view_body: 2 # at least 5 views to triangulate
            dist_max: 30 # pixel
            dist_track: 100 # 100mm；
        cfg_track:
          max_person: 100
          #final_ranges: [[-5, -10, -1], [15, 25, 5]] # Ranges of the final output, only used for filtering at output time
          final_max_person: 50
  at_final:
    collect:
      args:
        min_frame: 4
    fitting_each_person:
      args:
        stages:
          refine_poses:
            args:
              loss:
                smooth:
                  weight: 5.
    vis_render:
      args:
        view_list: [3]
        scale: 1.