trainer_module: "easymocap.neuralbody_relight.renderer.render_wrapper.RenderWrapper"
trainer_args:
  renderer_module: "easymocap.neuralbody_relight.renderer.render_base.BaseRenderer"
  renderer_args:
    chunk: 2048
    white_bkgd: False
    use_occupancy: True
    N_samples: 64
    split: train
  loss:
    rgb:
      weight: 1.
      module: "easymocap.neuralbody_relight.renderer.render_loss.LossRGB"
      args:
        norm: "l2"

renderer_module: "easymocap.neuralbody_relight.renderer.render_base.BaseRenderer"
renderer_args:
  chunk: 8192
  white_bkgd: True
  use_occupancy: True
  N_samples: 64
  split: test
  
train:
  ep_iter: 1000
  epoch: 550
  save_ep: 1
  save_latest_ep: 5
  eval_ep: 100
  skip_eval: True
  batch_size: 1
  shuffle: True
  batch_sampler: "default"
  num_workers: 4
  collator: "default"